### ISSUE TITLE
Duplicate Database class

### ISSUE THREAD

**Issue by trollboy** [vespercore02/mymvc#2]
https://github.com/vespercore02/mymvc/blob/9dd7fad950b95f26badeded66a0be32505757724/Resources/config/config.php#L3

Database is declared twice. I recommend keeping it in Database.php and deleting it out of here.

**Comment by trollboy** [comment]
@vespercore02 it seems that you fixed this.  Are you cool closing this ticket?

**Comment by vespercore02** [comment]
sure this is good im now using this database instead the resource
