### ISSUE TITLE
Split HTML from PHP

### ISSUE THREAD

**Issue by trollboy** [vespercore02/mymvc#5]
Your php has html all through out it, it's good to separate these.

**Comment by vespercore02** [comment]
is this how to split html from PHP? 
[views/show_movies.php](url)

**Comment by trollboy** [comment]
I stand corrected!! I remember seeing some of your login logic returning ` return '<div> ERROR </div>'` or similar and that's considered bad form. I can't find anything else with that in there, so let's close this issue out as done.  

The rule is; a class or function should never have html in it without a good reason.
