### ISSUE TITLE
Docker Question

### ISSUE THREAD

**Issue by vespercore02** [vespercore02/mymvc#9]
@trollboy 
do i need to restart the server to the changes?

**Comment by trollboy** [comment]
Depends on the changes; for changes to the Dockerfile, you will have to restart the server and run a `docker-compose build` again.  For changes to php files, it should just automagically work.  If not, make sure you check that you have docker volumes configured properly for Windows 10.

**Comment by vespercore02** [comment]
noted on this.. i will check the volumes.. i will close this one you informed me well thank you very much
